repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: '^simulation/px4/models/'
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
        # Les fichiers de lancement ROS 2 et RViz utilisent des tags non standard.
        exclude: '^drone/ros2/dronoto_bringup/rviz/'
      - id: check-added-large-files
        args: [--maxkb=2048]
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.5
    hooks:
      - id: clang-format
        types_or: [c++, c]
