<?xml version="1.0"?>
<package format="3">
  <name>dronoto_mission</name>
  <version>0.1.0</version>
  <description>Exécutif de mission Dronoto : séquencement décollage, waypoints,
    atterrissage.</description>
  <maintainer email="ynebocin@gmail.com">Nicolas BENY</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>dronoto_msgs</depend>
  <depend>dronoto_core</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
