#!/bin/sh
#
# @name Dronoto x500 (Gazebo)
# @type Quadrotor x
#

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500_dronoto}

. ${R}etc/init.d/rc.mc_defaults

param set-default SIM_GZ_EN 1

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 1
param set-default SENS_EN_MAGSIM 1

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.15
param set-default CA_ROTOR0_PY 0.15
param set-default CA_ROTOR0_KM 0.05
param set-default CA_ROTOR1_PX -0.15
param set-default CA_ROTOR1_PY -0.15
param set-default CA_ROTOR1_KM 0.05
param set-default CA_ROTOR2_PX 0.15
param set-default CA_ROTOR2_PY -0.15
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.15
param set-default CA_ROTOR3_PY 0.15
param set-default CA_ROTOR3_KM -0.05

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150
param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000

# --- Parametres Dronoto ---
# Limites de mission : docs/architecture/03-simulation.md
param set-default MPC_XY_VEL_MAX 12.0
param set-default MPC_Z_VEL_MAX_UP 3.0
param set-default MPC_Z_VEL_MAX_DN 1.5
param set-default MPC_TKO_SPEED 1.5
param set-default MPC_LAND_SPEED 0.7

# Fenetre de tolerance offboard. Coherent avec le seuil STALE_SETPOINT de
# px4_interface : px4_interface republie a 20 Hz et bascule en maintien de
# position a 0,5 s, donc PX4 ne doit pas quitter offboard avant.
param set-default COM_OF_LOSS_T 0.5

# Autoriser l'armement sans radiocommande : indispensable en SITL headless.
param set-default COM_RC_IN_MODE 4
param set-default NAV_RCL_ACT 0
